<a href="https://colab.research.google.com/github/Mehmteren/Artificial-Intelligence-Projects-with-Python-Machine-Deep-Learning/blob/main/Mult%C4%B1pleLineerRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.metrics import mean_squared_error, r2_score
import statsmodels.api as sm
from sklearn import linear_model

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/ProjelerleYapayZMakineO/multilinearregression.csv", sep = ";")
df

alan  odasayisi  binayasi   fiyat
0   180          5        10  510000
1   225          4        18  508000
2   260          3         2  548000
3   320          6        10  650000
4   335          4         9  628000
5   345          5        14  632000
6   355          3         0  680000
7   400          4        10  725000

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(df[["alan", "odasayisi", "binayasi"]], df["fiyat"])

reg.predict([[230,4,10]])

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([530243.29284619])

In [ ]:
reg.predict([[230,4,10], [270,5,0], [240,1,14]])

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([530243.29284619, 611963.9057772 , 485325.07094213])

In [ ]:
reg.coef_

array([ 1018.99865454, 14893.82374984, -2606.68429997])

In [ ]:
reg.intercept_

262365.1503032055

In [ ]:
a = reg.intercept_
b1 = reg.coef_[0]
b2 = reg.coef_[1]
b3 = reg.coef_[2]

x1 = 230
x2 = 4
x3 = 10
y = a + b1*x1 + b2*x2 + b3*x3
y

530243.2928461881